### Train_Test_Split Fonksiyonu

Bu fonksiyon tek seferde veri setini, verdiğimiz parametrelere göre test ve train olarak ayırmamızı sağlar.

In [11]:
import numpy as np
from sklearn.model_selection import train_test_split

X = np.arange(10).reshape((5, 2))
y = range(5)

print(f"X: {X}")
print(f"y: {list(y)}")

X: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y: [0, 1, 2, 3, 4]


In [13]:
# random_state = tekrarlanabilir çıktı üretmek için kullanılır. Aynı tam sayı değeri her zaman aynı karıştırmayı (shuffling) kontrol eder.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


print("\nEğitim (train) setleri:")
print("X_train (özellikler):")
print(X_train)
print("y_train (hedefler):")
print(list(y_train))

print("\nTest (test) setleri:")
print("X_test (özellikler):")
print(X_test)
print("y_test (hedefler):")
print(list(y_test))


Eğitim (train) setleri:
X_train (özellikler):
[[4 5]
 [0 1]
 [6 7]]
y_train (hedefler):
[2, 0, 3]

Test (test) setleri:
X_test (özellikler):
[[2 3]
 [8 9]]
y_test (hedefler):
[1, 4]


### Veri Seti Ölçeklendirmesi - Normalization

Veri setindeki sayısal feature değerlerini makine öğrenmesi algoritmaları için normalize etmemiz gerekir. Çünkü makine öğrenmesi algoritmaları ortalması 0 olan ve varyansı 1 olan dağılımlarda daha iyi performans göstermektedir. Sklearn kütüphanesinde bulunan StandartScaler fonskiyonu ile her bir veri noktasının z_score'u hesaplanarak bu işlem yapılabilir.

z_score = (x - u) / s

In [14]:
# Standart Scaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler.fit(data) # İlgili veri seti için mean ve standart sapma değerleri hesaplanır.
normalize_data = scaler.transform(data) # Normalizasyon işlemini gerçekleştirir.

# Not: fit_transform ile eğitim veri seti için bu işlemi tek adımda gerçekleştirebiliriz.

normalize_data

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])